---
- name: Deploy Grafana Server systemd config
  template:
    src: grafana-server.systemd.j2
    dest: /etc/systemd/system/grafana-server.service
    owner: root
    group: root
    mode: 0755
  notify:
    - reload systemd
  when: ansible_service_mgr == 'systemd'

- name: Copy Grafana init script
  template:
    src: grafana-server.upstart.conf.j2
    dest: /etc/init/grafana-server.conf
    mode: 0644
    owner: root
    group: root
  register: upstart_init
  notify:
    - restart grafana-server
  when: ansible_service_mgr == 'upstart'

- name: Reload init scripts
  command: initctl reload-configuration
  when: upstart_init | changed
  notify:
    - restart grafana-server

- name: Deploy Grafana Config Ini file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: root
    mode: 0644
  notify:
      - restart grafana-server

- name: Deploy Grafana Default file
  template:
    src: grafana-default.j2
    dest: /etc/default/grafana
    owner: root
    group: root
    mode: 0644
  notify:
    - restart grafana-server

- meta: flush_handlers
