---
- name: Setup Grafana Wheezy Repository
  apt_repository:
    repo: "deb https://dl.bintray.com/haad/monasca xenial main"
    state: present
  register: add_grafana_apt
  until: add_grafana_apt | success
  retries: 5
  delay: 3

- name: Install Grafana Apt Key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 379CE192D401AB61
    state: present
  register: add_grafana_apt_key
  until: add_grafana_apt_key | success
  retries: 5
  delay: 3

- name: Update Apt repos
  apt:
    update_cache: yes
  register: update_cache
  until: update_cache | success
  retries: 5
  delay: 3

- name: Install Grafana
  apt:
    pkg: grafana
    force: yes
    state: latest
  register: install_grafana
  until: install_grafana | success
  retries: 5
  delay: 3

