---

- name: Install System dependiences
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ dep_packages }}'

- include: install_go.yml

- include: DebianInst.yml
  when: "ansible_os_family == 'Debian'"

- include: RedHatInst.yml
  when: "ansible_os_family == 'RedHat'"

- name: Create required directories
  file:
    state: directory
    path: '{{ item }}'
    owner: grafana
    recurse: yes
  with_items:
    - '{{ grafana_log_dir }}'
    - '{{ grafana_data_dir }}'
    - '{{ grafana_plugins_dir }}'